### ISSUE TITLE
Error when bundling a Godot binary

### ISSUE THREAD

**Issue by Calinou** [intoli/exodus#15]
**Operating system, Python and Exodus version:** Fedora 27, Python 3.6.4, Exodus 1.1.6

Attempting to bundle a self-compiled [Godot](https://godotengine.org) binary results in this error:

```
❯ exodus godot.x11.opt.tools.64 -v
Traceback (most recent call last):
  File "/home/hugo/.local/bin/exodus", line 11, in <module>
    sys.exit(main())
  File "/home/hugo/.local/lib/python3.6/site-packages/exodus_bundler/cli.py", line 118, in main
    create_bundle(**args)
  File "/home/hugo/.local/lib/python3.6/site-packages/exodus_bundler/bundling.py", line 34, in create_bundle
    root_directory = create_unpackaged_bundle(executables, rename=rename, ldd=ldd)
  File "/home/hugo/.local/lib/python3.6/site-packages/exodus_bundler/bundling.py", line 124, in create_unpackaged_bundle
    'The same library filename has been included more than once in a bundle.'
AssertionError: The same library filename has been included more than once in a bundle.
```

Here's a [ZIP archive containing the binary](https://github.com/intoli/exodus/files/1693574/godot.x11.opt.tools.64.zip); it is compiled on Fedora 27 with GCC 7.2.1 with LTO enabled. (I've run into the same issue when bundling the Godot binary compiled using Clang with LTO disabled.)

On the same system, I am able to create bundles of other applications such as [micro](https://micro-editor.github.io/) or [ezQuake](https://ezquake.github.io).

**Comment by sangaline** [comment]
@Calinou Thank you for the detailed error report, it was very helpful in reproducing the error. The underlying issue should be resolved as of v1.1.8 due to #17. Using that new version, I was able to successfully bundle the Godot binary that you provided on Fedora 27 and relocate it to another machine.

Please let me know if you're still running into any problems and I'll reopen this.
