### ISSUE TITLE
FATAL: kernel too old

### ISSUE THREAD

**Issue by e-volusian** [intoli/exodus#25]
Please include the following information if you're reporting an issue.

request|response
--|--
Which operating system you're using.|source:Ubuntu 17.1, dest: Centos 6.5
Which Python version.|source: Python 2.7.14
Which exodus package version.|release v1.1.9 <br><br> **NOTE** *exodus* and/or *exodus -h* don't print a version number
The command that you're running | `exodus --verbose /usr/bin/duc \| ssh my.destination.server.com`
The full output of the command.|Pseudo-terminal will not be allocated because stdin is not a terminal<br>Installing executable bundle in "/home/speare/.exodus"...<br>Successfully installed, be sure to add /home/speare/.exodus\/bin to your $PATH.
`which $BINARY`|/usr/bin/duc

I can provide rest of details on request. Not sure they're relevant here.

Output of `uname -r`

source|dest
--|--
4.13.0-32-generic|2.6.32-696.10.3.el6.x86_64

Attempting to run `~/.exodus/bin/duc` at destination returns `FATAL: kernel too old`

Any way to make this work?

**Comment by sangaline** [comment]
Thanks for the detailed error report, but I'm not sure if there's any way around it if the glibc version is incompatible with the kernel. Something that you could try is digging into the corresponding `~/.exodus/bundles/.../lib/` for the `duc` bundle, and then deleting the file starting with `libc.so`. This would make the linker fall back to the local system version of glibc. That will obviously be compatible with the kernel, but there's a good change that the rest of the transported binaries won't be compatible with the system glibc. Part of me is also curious to know what would happen if you patch the binary so that the `.note.ABI-tag` lies about the minimum supported kernel version. Realistically, it would probably just crash.

Beyond that, the only workaround I can think of here is trying to make the bundle on a system with an older kernel version that might be compatible. You could potentially do this in a docker container on the newer machine.

Sorry that I couldn't be of more help here, but I'll definitely add this to the "Known Limitations" section of the README.

**Comment by e-volusian** [comment]
No worries. I figured this would be the answer. I did remove `~/.exodus/bundles/*/lib/libc.so.6` with same result. Thanks for checking!
