### ISSUE TITLE
Make exodus compliant with XDG base directory specification

### ISSUE THREAD

**Issue by smrcka** [intoli/exodus#42]
Exodus uses $HOME/.exodus directory as storage on a target system. Such a "yet-another-dot-file in home directory" has issues with many users. Some readings on that:
 - https://lists.freedesktop.org/archives/xdg/2013-August/012872.html

Please make exodus compliant with XDG base-directory specification:
  - https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html
  - https://www.freedesktop.org/software/systemd/man/file-hierarchy.html#Home%20Directory

For instance:
  - $HOME/.exodus/bundle -> $HOME/.local/share/exodus/bundle
  - $HOME/.exodus/data -> $HOME/.localshare/exodus/data
  - $HOME/.exodus/bin -> $HOME/.local/bin

**Comment by sangaline** [comment]
I had thought about doing this originally, and ultimately decided against it. I'm open to reconsidering, but let me explain my original thought process.

The default system-installation directory for Exodus bundles is `/opt/exodus/`. This seems like the most appropriate location for a *fully self-contained* bundle of software in my opinion. It's out of the question that software be installed directly in `/` or `/usr/local/` because mixing incompatible shared objects in the same directories would be a mess. Additionally, it would make uninstalling bundles extremely difficult because there's no central package registry.

My understanding of `~/.local/` is that it's analogous to `/` or `/usr/local/`. Binaries should be installed in `~/.local/bin/`, libraries inside of `~/.local/lib/`, and shared application resources in `~/.local/share/`. I think that the same arguments against extracting bundles in `/` or `/usr/local/` applies to `~/.local/` too. You didn't suggest installing libraries directly in `~/.local/lib`, but `~/.local/share/` doesn't really feel like a great fit either. From one of your links, this directory is supposed to be for "resources shared between multiple packages, such as fonts or artwork." Based on that, and the name, it seems a lot more like `/usr/share/` than `/opt/`.

I'm definitely sympathetic to "yet-another-dot-file," but I think the real issues that motivated the spec were a proliferation of configuration files and cache data (which your first link supports). These have very clear solutions with `~/.cache` and `~/.config`. The `~/.local/` hierarchy offers a good solution to locally installing packages that mirror the structure of system-level packages. There's unfortunately not an `~/.opt/` or a `~/.local/opt`, which it seems would be the appropriate fit for Exodus.

So the question is whether it's better to shoehorn the bundles into a directory that they're not a particularly great fit for, or to just create a `~/.exodus` directory, inform the user about it, and make it easy to delete. I personally would prefer the latter as a user.

Also, the bundles can be extracted anywhere, so you can always run

```bash
./exodus-htop-bundle.sh ~/.local/share/exodus
```

if you prefer to extract things in `~/.local/share/exodus`.

**Comment by smrcka** [comment]
I understand--that make sense to me. When I first thought about XDG directories, I considered storing libraries directly to `~/.local/lib/` (since they can be shared) and link to them via symlink from `~/.local/share/exodus/bundle/PROGRAM/PROGRAM_SPECIFIC_LIB`.

Anyway, I **personally** preffer to not make yet-another-dot-file and since more applications make it easy by moving it from home to `./local/share` I would like to see it in `~/.local/share/exodus`.

**Comment by sangaline** [comment]
I do understand your preference here, but I'm still not convinced that the Exodus bundles *clearly* belong in `~/.local/share`. I definitely think that the installation location should be easy for a user to change however. I mentioned above that you can pass a directory to an installation script, and the installation scripts are essentially just self-extracting tarballs anyway. You can pipe out the tarball directly using the `-t` option on Exodus, and then control the tar extraction directly. The following would place the `exodus` bundle directory inside of `~/.local/share`.

```
exodus -t htop | ssh intoli.com "tar -C ~/.local/share -zx"
```
